config:
  ignore:
    files:
      - index.html
    commits:
      - <commit_hash>
techstack:
   cloud:
      aws: 
         - AWS Elastic Compute Cloud (EC2)
         - AWS EC2 Container Service (ECS)
         - AWS EC2 Container Service (ECS1)
         - AWS EC2 Container Service (ECS2)
         - AWS EC2 Container Service (ECS3)
         - AWS EC2 Container Service (ECS4)
         - AWS EC2 Container Service (ECS5)

      azure: 
         - Azure Virtual Machines
         - Azure Load Balancer
               
   utilities:
      - centos:8.4
   Database / NoSQL / Cache:
      - mysql:8.0
      - mongodb